server:
  port: 8204
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.56.102:8848
    gateway:
      routes:
        - id: user
          uri: lb://paicoding-user
          predicates:
            - Path=/user/**
        - id: origin
          uri: lb://paicoding-origin
          predicates:
            - Path=/article/**,/rest/**
        - id: article
          uri: lb://paicoding-article
          predicates:
            - Path=/temptest/**

#  datasource: #单数据源
#    url: jdbc:mysql://192.168.56.102:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
  main:
    # 引入下面这个配置，主要是为了解决自定义实现的多数据源功能，自主注册的datasource替换默认的
    allow-bean-definition-overriding: true
    allow-circular-references: true


# 默认的数据库名
database:
  name: pai_coding
  username: root
  password: 123456